### ISSUE TITLE
通过API 实现 k8s 集群的安装

### ISSUE THREAD

**Issue by caoyingjunz** [caoyingjunz/pixiu#167]
两种模式，一个是标准导入集群，用户只需要把已有k8s的集群config导入即可，一种是自建的，需要选择k8s的配置信息，由pixiu完成k8s整个集群的启动

标准的，直接api，我们会一层优化，解除对k8s api的压力，自建集群，会通过grpc调用到自己的驱动上，完成创建，驱动后端会通过我之前分享的一个部署项目完成部署

**Comment by chenghongxi** [comment]
go
