### ISSUE TITLE
docker run 报错

### ISSUE THREAD

**Issue by lyk-ops** [caoyingjunz/pixiu#435]
root@master-01 ~]# docker ps |grep pixiu
8925aa181820   harbor.cloud.pixiuio.com/pixiuio/pixiu-aio   "/docker-entrypoint.…"   10 minutes ago   Restarting (1) 42 seconds ago             pixiu-aio
d701a70ae947   harbor.cloud.pixiuio.com/pixiuio/mysql:5.7   "docker-entrypoint.s…"   14 minutes ago   Up 14 minutes                             mariadb
[root@master-01 ~]# docker logs 8925aa181820
+ '[[' '!' -d /etc/pixiu ]]
+ '[[' -e /usr/share/nginx/html/pixiu/config.json ]]
+ '[[' -e /etc/pixiu/config.json ]]
+ cp /etc/pixiu/config.json /usr/share/nginx/html/pixiu/config.json
Starting pixiu dashboard service
+ echo 'Starting pixiu dashboard service'
+ nginx -g 'daemon on;'
2024/06/20 02:44:03 [notice] 9#9: using the "epoll" event method
2024/06/20 02:44:03 [notice] 9#9: nginx/1.27.0
2024/06/20 02:44:03 [notice] 9#9: built by gcc 13.2.1 20231014 (Alpine 13.2.1_git20231014)
2024/06/20 02:44:03 [notice] 9#9: OS: Linux 3.10.0-1127.19.1.el7.x86_64
2024/06/20 02:44:03 [notice] 9#9: getrlimit(RLIMIT_NOFILE): 1048576:1048576
2024/06/20 02:44:03 [notice] 10#10: start worker processes
2024/06/20 02:44:03 [notice] 10#10: start worker process 11
2024/06/20 02:44:03 [notice] 10#10: start worker process 12
2024/06/20 02:44:03 [notice] 10#10: start worker process 13
2024/06/20 02:44:03 [notice] 10#10: start worker process 14
2024/06/20 02:44:03 [notice] 10#10: start worker process 15
Starting pixiu backend service
2024/06/20 02:44:03 [notice] 10#10: start worker process 16
+ echo 'Starting pixiu backend service'
+ /app
2024/06/20 02:44:03 [notice] 10#10: start worker process 18
2024/06/20 02:44:03 [notice] 10#10: start worker process 19
2024/06/20 02:44:03 [notice] 10#10: start worker process 20
2024/06/20 02:44:03 [notice] 10#10: start worker process 21
2024/06/20 02:44:03 [notice] 10#10: start worker process 22
2024/06/20 02:44:03 [notice] 10#10: start worker process 23
dial tcp: lookup pixiu on 114.114.114.114:53: no such host
+ '[[' '!' -d /etc/pixiu ]]
+ '[[' -e /usr/share/nginx/html/pixiu/config.json ]]
+ rm -rf /usr/share/nginx/html/pixiu/config.json
+ '[[' -e /etc/pixiu/config.json ]]
+ cp /etc/pixiu/config.json /usr/share/nginx/html/pixiu/config.json
+ echo 'Starting pixiu dashboard service'
+ nginx -g 'daemon on;'

**Comment by caoyingjunz** [comment]
看起来是配置有问题，可以贴一下/etc/pixiu/config.yaml， 数据库的host需要改成实际的配置

**Comment by caoyingjunz** [comment]
没问题的话，就先关issue了
